# Generated by Django 3.2 on 2021-12-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=255)),
                ('main_description', models.CharField(max_length=255)),
                ('main_image', models.ImageField(upload_to='')),
                ('missiya_image', models.ImageField(upload_to='')),
                ('korporativ_medeniyyet_image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Haqqında',
                'verbose_name_plural': 'Haqqında',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=255)),
                ('map_button_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Əlaqə Səhifəsi',
                'verbose_name_plural': 'Əlaqə Səhifəsi',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_title', models.CharField(max_length=255)),
                ('cover_description', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(upload_to='')),
                ('niye_biz_title', models.CharField(max_length=255)),
                ('niye_biz_description', models.CharField(max_length=255)),
                ('xidmetler_title', models.CharField(max_length=255)),
                ('xidmetler_description', models.CharField(max_length=255)),
                ('xidmetler_image', models.ImageField(upload_to='')),
                ('layiheler_title', models.CharField(max_length=255)),
                ('layiheler_description', models.CharField(max_length=255)),
                ('layiheler_image', models.ImageField(upload_to='')),
                ('musteriler_title', models.CharField(max_length=255)),
                ('musteriler_description', models.CharField(max_length=255)),
                ('musteriler_image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Ana Səhifə',
                'verbose_name_plural': 'Ana Səhifə',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=255)),
                ('main_description', models.CharField(max_length=255)),
                ('main_image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Tərəfdaşlar',
                'verbose_name_plural': 'Tərəfdaşlar',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=255)),
                ('main_description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Layihələr',
                'verbose_name_plural': 'Layihələr',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=255)),
                ('main_description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Xidmətlər',
                'verbose_name_plural': 'Xidmətlər',
            },
        ),
    ]
