# Generated by Django 3.2 on 2021-12-24 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='ServiceStatik',
        ),
    ]
