# Generated by Django 3.2 on 2021-12-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0003_rename_project_projectstatik'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='success_text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
