# Generated by Django 3.2 on 2023-09-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0004_contact_success_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='xidmetler_description',
            new_name='mehsullar_description',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='xidmetler_image',
            new_name='mehsullar_image',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='xidmetler_title',
            new_name='mehsullar_title',
        ),
    ]
