# Generated by Django 3.2 on 2023-10-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0005_auto_20230921_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='main_video_back',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
