# Generated by Django 3.2 on 2023-10-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statik', '0006_home_main_video_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='main_description_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='main_description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='main_description_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='main_title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='main_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='main_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='main_title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='main_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='main_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='map_button_text_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='map_button_text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='map_button_text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='success_text_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='success_text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='success_text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='cover_description_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='cover_description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='cover_description_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='cover_title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='cover_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='cover_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='layiheler_description_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='layiheler_description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='layiheler_description_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='layiheler_title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='layiheler_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='layiheler_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='mehsullar_description_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='mehsullar_description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='mehsullar_description_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='mehsullar_title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='mehsullar_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='mehsullar_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='musteriler_description_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='musteriler_description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='musteriler_description_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='musteriler_title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='musteriler_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='musteriler_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='niye_biz_description_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='niye_biz_description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='niye_biz_description_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='niye_biz_title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='niye_biz_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='niye_biz_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partners',
            name='main_description_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partners',
            name='main_description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partners',
            name='main_description_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partners',
            name='main_title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partners',
            name='main_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partners',
            name='main_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectstatik',
            name='main_description_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectstatik',
            name='main_description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectstatik',
            name='main_description_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectstatik',
            name='main_title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectstatik',
            name='main_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectstatik',
            name='main_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicestatik',
            name='main_description_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicestatik',
            name='main_description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicestatik',
            name='main_description_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicestatik',
            name='main_title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicestatik',
            name='main_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicestatik',
            name='main_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
