# Generated by Django 3.2 on 2023-09-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productspage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsPage',
            new_name='CategoriesPage',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='CategoryImage',
        ),
    ]
