# Generated by Django 3.2 on 2023-09-22 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20230922_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product.model'),
        ),
    ]
