# Generated by Django 3.2 on 2023-09-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20230929_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_models_text',
            field=models.TextField(default='What kind of elevator do you need?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sub_models_title',
            field=models.CharField(default='See our future-proof, energy efficient elevators with enabled IoT connectivity designed for improved people and material flow.', max_length=256),
            preserve_default=False,
        ),
    ]
