# Generated by Django 3.2 on 2023-10-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20230929_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='name_az',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_az',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value_ru',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
