# Generated by Django 3.2 on 2023-10-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20231009_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriespage',
            name='page_header_az',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='categoriespage',
            name='page_header_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='categoriespage',
            name='page_header_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='categoriespage',
            name='page_header_text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='categoriespage',
            name='page_header_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='categoriespage',
            name='page_header_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='excerpt_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='excerpt_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='excerpt_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_az',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
