# Generated by Django 3.2 on 2023-10-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20231009_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='name_az',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dark_section_text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dark_section_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dark_section_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dark_section_title_az',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dark_section_title_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dark_section_title_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='excerpt_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='excerpt_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='excerpt_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_az',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_models_text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_models_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_models_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_models_title_az',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_models_title_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_models_title_ru',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
