# Generated by Django 3.2 on 2023-10-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='excerpt_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='excerpt_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='excerpt_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='name_az',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='offerspage',
            name='page_header_az',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='offerspage',
            name='page_header_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='offerspage',
            name='page_header_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='offerspage',
            name='page_header_text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offerspage',
            name='page_header_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offerspage',
            name='page_header_text_ru',
            field=models.TextField(null=True),
        ),
    ]
