# Generated by Django 3.2 on 2021-12-24 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Müştərilər',
                'verbose_name_plural': 'Müştərilər',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('elaqe', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Yazılan Mesajlar',
                'verbose_name_plural': 'Yazılan Mesajlar',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Tərəfdaşlar',
                'verbose_name_plural': 'Tərəfdaşlar',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='')),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('veziyyeti', models.CharField(max_length=255)),
                ('tip', models.CharField(max_length=255)),
                ('sahe', models.CharField(max_length=255)),
                ('muddet', models.CharField(max_length=255)),
                ('yer', models.CharField(max_length=255)),
                ('musteri', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Layihələr',
                'verbose_name_plural': 'Layihələr',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Xidmətlər',
                'verbose_name_plural': 'Xidmətlər',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='')),
                ('url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Sosial Media Linkləri',
                'verbose_name_plural': 'Sosial Media Linkləri',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('position', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Komanda',
                'verbose_name_plural': 'Komanda',
            },
        ),
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Komanda Kateqoriyalar',
                'verbose_name_plural': 'Komanda Kateqoriyalar',
            },
        ),
        migrations.AlterModelOptions(
            name='general',
            options={'verbose_name': 'Ümumi məlumatlar', 'verbose_name_plural': 'Ümumi məlumatlar'},
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='home.project')),
            ],
        ),
    ]
