# Generated by Django 3.2 on 2021-12-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211224_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='sirketimiz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
