# Generated by Django 3.2 on 2021-12-24 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_general_sirketimiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='home.teamcategory'),
            preserve_default=False,
        ),
    ]
