# Generated by Django 3.2 on 2021-12-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_team_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='favicon',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='general',
            name='meta_description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='general',
            name='meta_keywords',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='general',
            name='meta_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
