# Generated by Django 3.2 on 2021-12-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211224_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='logo_white',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
