# Generated by Django 3.2 on 2021-12-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_general_logo_white'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='icon_white',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
