# Generated by Django 3.2 on 2021-12-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_social_icon_white'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='icon_white',
        ),
        migrations.AddField(
            model_name='social',
            name='icon_font_tag',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
