# Generated by Django 3.2 on 2021-12-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211224_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='deyerlerimiz_title_text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='general',
            name='korporativ_medeniyyet_title_text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='general',
            name='our_mission_title_text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='general',
            name='sirketimiz_title_text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
