# Generated by Django 3.2 on 2023-09-21 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20230922_0016'),
        ('home', '0009_auto_20211230_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='product.category'),
        ),
    ]
