# Generated by Django 3.2 on 2023-09-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_project_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfisUnvanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
    ]
