# Generated by Django 3.2 on 2023-09-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_ofisunvanlar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofisunvanlar',
            options={'ordering': ('sort',)},
        ),
        migrations.AddField(
            model_name='ofisunvanlar',
            name='sort',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
