# Generated by Django 3.2 on 2023-09-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20230922_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofisunvanlar',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
