# Generated by Django 3.2 on 2023-10-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_ofisunvanlar_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='address_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='address_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='address_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='sirketimiz_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='sirketimiz_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='sirketimiz_ru',
            field=models.TextField(null=True),
        ),
    ]
