# Generated by Django 3.2 on 2023-10-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20231009_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='copyright_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='copyright_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='copyright_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='deyerlerimiz_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='deyerlerimiz_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='deyerlerimiz_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='deyerlerimiz_title_text_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='deyerlerimiz_title_text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='deyerlerimiz_title_text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='korporativ_medeniyyet_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='korporativ_medeniyyet_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='korporativ_medeniyyet_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='korporativ_medeniyyet_title_text_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='korporativ_medeniyyet_title_text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='korporativ_medeniyyet_title_text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='our_mission_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='our_mission_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='our_mission_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='our_mission_title_text_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='our_mission_title_text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='our_mission_title_text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='sirketimiz_title_text_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='sirketimiz_title_text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='general',
            name='sirketimiz_title_text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
