# Generated by Django 3.2 on 2023-10-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20231009_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='position_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='position_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='position_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teamcategory',
            name='name_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teamcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teamcategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
