# Generated by Django 3.2 on 2023-10-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20231009_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofisunvanlar',
            name='address_az',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ofisunvanlar',
            name='address_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ofisunvanlar',
            name='address_ru',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
